#! /bin/bash 

ver="v0.3.1"

tools_alacritty=-V
tools_arduino=--version
tools_awk=--version
tools_bash=--version
tools_cargo=--version
tools_clang=--version
tools_cmake=--version
tools_ccmake=--version
tools_conky=-v
tools_convert=--version
tools_curl=--version
tools_direnv=version
tools_docker=-v
tools_dotnet=--version
tools_elixir=-v
tools_exa=-v
tools_ffmpeg=-version
tools_firefox=-v
tools_fzf=--version
tools_gcc=--version
tools_gdb=--version
tools_gem=-v
tools_gimp=-version
tools_git=--version
tools_go=version
tools_gradle=--version
tools_grep=-V
tools_haxe=-version
tools_haxelib=version
tools_inkscape=--version
tools_java=-version
tools_javac=-version
tools_kodi=-v
tools_kotlin=-version
tools_lua=-v
tools_magick=--version
tools_man=--version
tools_make=-v
tools_nano=--version
tools_node=-v
tools_nokogiri=-v
tools_nordvpn=-v
tools_npm=-v
tools_nvim=-version
tools_pacman=--version
tools_perl=-v
tools_python=-V
tools_python2=-V
tools_python3=-V
tools_rake=--version
tools_ranger=--version
tools_rbenv=-v
tools_restic=version
tools_rg=-V
tools_rsync=--version
tools_rubocop=-v
tools_ruby=-v
tools_rustc=--version
tools_screen=-v
tools_sed=--version
tools_sidekiq=--version
tools_slack=-v
tools_ssh=-V
tools_swift=-version
tools_tmux=-V
tools_valgrind=--version
tools_version=-v
tools_vi=-version
tools_vim=-version
tools_vlc=--version
tools_wget=--version
tools_yarn=version
tools_zsh=--version


# User forgot to specify the program or a flag
if [ -z $1 ]
then
  echo "Usage: version <program>"
  exit
fi

# Display help
if [ $1 == -h ]
then
  echo "version displays the versions of programs you have installed."
  echo ""
  echo "Usage:"
  echo "  version <program>    display version of program"
  echo "                       (if known and installed)"
  echo "  version -h           display this help"
  echo "  version -l           display a list of known programs"
  echo "  version -c           display count of known programs"
  echo "  version -v           display version of version"
  echo "                       (yes, 'version version' also works!)"
  exit
fi

# Display recognized program count
if [ $1 == -c ]
then
  count=$(egrep -o "^tools_" $(which version) | wc -l)
  echo "I know how to find the versions of $count programs!"
  exit
fi

# Display version of version
if [ $1 == -v ]
then
  echo "version $ver"
  exit
fi

# Display all the tools we know
if [ $1 == -l ]
then
  egrep -o "^tools_[^=]*" $(which version) | grep -oP "tools_\K(.*)"
  exit
fi


tool=tools_$1
version_arg=${!tool}

# do we know about this program?
if [ -z $version_arg ]
then
  echo "I don't know how to find the version of '$1'."
  echo "If you figure it out, let me know at https://github.com/bit101/version"
  exit
fi 

# display the correct command for the user
echo "Command: $1 $version_arg"

# does the user have this program installed?
if ! command -v $1 &> /dev/null
then
  echo "But '$1' does not seem to be installed"
  exit
fi

# success. make the call to display the version.
$1 $version_arg

