#! /bin/bash 

ver="v0.3.0"

declare -A tools
tools[alacritty]=-V
tools[arduino]=--version
tools[awk]=--version
tools[bash]=--version
tools[clang]=--version
tools[conky]=-v
tools[convert]=--version
tools[dotnet]=--version
tools[exa]=-v
tools[ffmpeg]=-version
tools[firefox]=-v
tools[fzf]=--version
tools[gcc]=--version
tools[gdb]=--version
tools[gimp]=-version
tools[git]=--version
tools[go]=version
tools[gradle]=--version
tools[grep]=-V
tools[haxe]=-version
tools[haxelib]=version
tools[inkscape]=--version
tools[java]=-version
tools[javac]=-version
tools[kodi]=-v
tools[kotlin]=-version
tools[lua]=-v
tools[magick]=--version
tools[man]=--version
tools[make]=-v
tools[nano]=-version
tools[node]=-v
tools[nordvpn]=-v
tools[npm]=-v
tools[nvim]=-version
tools[perl]=-v
tools[python]=-V
tools[python2]=-V
tools[python3]=-V
tools[ranger]=--version
tools[rbenv]=-v
tools[restic]=version
tools[rg]=-V
tools[rsync]=--version
tools[ruby]=-v
tools[rustc]=--version
tools[sed]=--version
tools[slack]=-v
tools[ssh]=-V
tools[swift]=-version
tools[tmux]=-V
tools[version]=-v
tools[vi]=-version
tools[vim]=-version
tools[vlc]=--version
tools[yarn]=version
tools[zsh]=--version

# User forgot to specify the program or a flag
if [ -z $1 ]
then
  echo "Usage: version <program>"
  exit
fi

# Display help
if [ $1 == -h ]
then
  echo "version displays the versions of programs you have installed."
  echo ""
  echo "Usage:"
  echo "  version <program>    display version of program"
  echo "                       (if known and installed)"
  echo "  version -h           display this help"
  echo "  version -c           display count of known programs"
  echo "  version -v           display version of version"
  echo "                       (yes, 'version version' also works!)"
  exit
fi

# Display recognized program count
if [ $1 == -c ]
then
  count=${#tools[@]}
  echo "I know how to find the versions of $count programs!"
  exit
fi

# Display version of version
if [ $1 == -v ]
then
  echo "version $ver"
  exit
fi

# User does not have that program installed
if ! command -v $1 &> /dev/null
then
    echo "'$1' does not seem to be installed"
    exit
fi

# Display the version if we know about the tool
if [ ${tools[$1]+_} ]
then
  # success
  $1 ${tools[$1]}
else
  # don't know that one
  echo "I don't know how to find the version of '$1'."
  echo "If you figure it out, let me know at https://github.com/bit101/version"
fi
